import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";
import localFont from "next/font/local";
import { Anton } from "next/font/google";
import AuthSessionProvider from "@/lib/AuthProvider";
export const myLocalFont = localFont({
  src: [
    {
      path: "./font/new_science.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/new_science_bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-local",
});

const antons = Anton({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${myLocalFont.variable} ${antons.variable} antialiased`}
      >
        <AuthSessionProvider>
          <NextThemesProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NextTopLoader
              color="orange"
              initialPosition={0.08}
              crawlSpeed={200}
              height={2}
              showSpinner={false}
              crawl={true}
              easing="ease"
              speed={200}
              shadow="0 0 5px #2299DD,0 0 5px #2299DD"
            />
            {children}
            <Toaster position="bottom-center" />
          </NextThemesProvider>{" "}
        </AuthSessionProvider>
      </body>
    </html>
  );
}
